---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
apiVersion: kuttl.dev/v1beta1
kind: TestSuite
name: e2e
testDirs:
  - tests/
timeout: 600
parallel: 1
namespace: default
commands:
  - command: kubectl apply -f https://raw.githubusercontent.com/kudobuilder/kuttl/main/crds/testassert_crd.yaml
