---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2024
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check End-to-End (On Demand)
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '**.go'
      - '**.sh'
      - '!.github/*'
  pull_request_review:
    types:
      - submitted
jobs:
  check-scripts-format:
    if: >-
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.state == 'approved'
      ) || github.event_name != 'pull_request_review'
    name: Check scripts format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: -i 4 -s
        with:
          sh_checker_shellcheck_disable: true
  functional-test:
    name: Check functional tests
    needs: check-scripts-format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Deploy Nephio services
        working-directory: ./scripts
        env:
          DEBUG: true
          ENABLE_FUNC_TEST: true
        run: ./main.sh
      - name: Install KUTTL
        env:
          KUTTL_VERSION: 0.16.0
        run: |
          curl -fsSL -o /usr/local/bin/kubectl-kuttl "https://github.com/kudobuilder/kuttl/releases/download/v${KUTTL_VERSION}/kubectl-kuttl_${KUTTL_VERSION}_$(uname | tr '[:upper:]' '[:lower:]')_$(uname -m)"
          chmod +x /usr/local/bin/kubectl-kuttl
      - name: Run integration tests
        run: kubectl-kuttl test
      - name: Export logs
        if: always()
        run: |
          kind export logs --name mgmt -v 4 ./_artifacts/logs
      - name: Upload mgmt cluster logs
        if: always()
        uses: actions/upload-artifact@v4.3.3
        with:
          name: kind-mgmt-logs-${{ github.run_id }}
          path: ./_artifacts/logs
